FROM node
MAINTAINER Alfred Francis

RUN mkdir app
WORKDIR /app

ENV BANNANA_VERSION 1.6.12

RUN mkdir -p /app/banana && \
    wget https://github.com/lucidworks/banana/archive/v$BANNANA_VERSION.tar.gz -O /app/banana.tar.gz && \
    tar -C /app/banana -xvf /app/banana.tar.gz --strip-components=1 &&\
    cd /app/banana && \
    npm install 

WORKDIR /app/banana